name: sahashop_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # Xep    A - Z
  curved_navigation_bar: ^0.3.7
  cupertino_icons: ^1.0.2
  cached_network_image: ^2.5.1
  carousel_slider: ^3.0.0
  dio: ^3.0.10
  dropdown_below: ^0.0.7
  device_info: ^2.0.0
  dotted_border: ^1.0.7
  empty_widget: ^0.0.1
  multi_image_picker: ^4.8.0
  flash: ^1.5.1
  flutter_absolute_path: ^1.0.6
  flutter_staggered_grid_view: ^0.4.0
  flutter_easyloading: ^3.0.0
  flutter_image_compress: ^1.0.0
  flutter_chips_input: ^1.9.5
  flutter_svg: ^0.19.3
  flutter_spinkit: ^5.0.0
  flutter_colorpicker: ^0.4.0
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.3.0
  http_parser: ^3.1.2
  hive: ^1.4.4+1
  get: ^3.26.0
  smart_select: ^4.3.2
  shimmer: ^1.1.1
  sticky_headers: ^0.1.8
  image_picker: ^0.6.7+7
  intl: ^0.17.0
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  path_provider: ^2.0.1
  retrofit: ^1.3.4+1
  unicorndial: ^1.1.5
  shared_preferences: ^2.0.5
  flutter_datetime_picker: ^1.5.1




dev_dependencies:
  retrofit_generator: ^1.3.7
  hive_generator: ^0.8.2
  build_runner: ^1.10.1

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: balsamiq_bold
      fonts:
        - asset: assets/fonts/balsamiq_sans/BalsamiqSans-Bold.ttf
          weight: 700
    - family: balsamiq_regular
      fonts:
        - asset: assets/fonts/balsamiq_sans/BalsamiqSans-Regular.ttf
          weight: 700
    - family: creepster_regular
      fonts:
        - asset: assets/fonts/creepsters/Creepster-Regular.ttf
          weight: 700
    - family: lato_regular
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 700
    - family: neucha_regular
      fonts:
        - asset: assets/fonts/neucha_regular/Neucha-Regular.ttf
          weight: 700
    - family: nunito_bold
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
    - family: nunito_regular
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 700
    - family: varela_regular
      fonts:
        - asset: assets/fonts/varela_regular/VarelaRound-Regular.ttf
          weight: 700
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/images/
    - assets/icons/
    - assets/saha_loading.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
