enum TYPE_ACTION {
  QR,
  SCORE,
  CALL,
  MESSAGE_TO_SHOP,
  VOUCHER,
  PRODUCTS_TOP_SALES,
  PRODUCTS_DISCOUNT,
  PRODUCTS_NEW,
  //////
  LINK,
  PRODUCT,
  CATEGORY_PRODUCT,
  CATEGORY_POST,
  POST,
}

final Map mapTypeAction = {
  TYPE_ACTION.QR: "QR",
  TYPE_ACTION.SCORE: "SCORE",
  TYPE_ACTION.CALL: "CALL",
  TYPE_ACTION.MESSAGE_TO_SHOP: "MESSAGE_TO_SHOP",
  TYPE_ACTION.VOUCHER: "VOUCHER",
  TYPE_ACTION.PRODUCTS_TOP_SALES: "PRODUCTS_TOP_SALES",
  TYPE_ACTION.PRODUCTS_DISCOUNT: "PRODUCTS_DISCOUNT",
  TYPE_ACTION.PRODUCTS_NEW: "PRODUCTS_NEW",
  ////
  TYPE_ACTION.LINK: "LINK",
  TYPE_ACTION.PRODUCT: "PRODUCT",
  TYPE_ACTION.CATEGORY_PRODUCT: "CATEGORY_PRODUCT",
  TYPE_ACTION.CATEGORY_POST: "CATEGORY_POST",
  TYPE_ACTION.POST: "POST",
};
