const USER_TOKEN = "USER_TOKEN";
const CURRENT_STORE_CODE = "CURRENT_STORE_CODE";
const CURRENT_USER_ID = "CURRENT_USER_ID";
const CURRENT_DATA_STATUS = "CURRENT_DATA_STATUS";
const CUSTOMER_TOKEN = "CUSTOMER_TOKEN";
