import 'package:sahashop_user/model/info_address.dart';

List<InfoAddress> LIST_ADDRESS_EXAMPLE = [
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
  InfoAddress(
    id: 1,
    storeId: 1,
    name: "Nguyen Duc Hieu",
    phone: "0342362909",
    addressDetail: "67/39 Hem vuon dieu",
    country: "Viet Nam",
    city: "TH.HCM",
    district: "Quan 7",
    wards: "Phuong tan quy",
  ),
];
